/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResultRouteImport } from './routes/result'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstructionsModeIdRouteImport } from './routes/instructions.$modeId'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsModeIdRoute = InstructionsModeIdRouteImport.update({
  id: '/instructions/$modeId',
  path: '/instructions/$modeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modes': typeof ModesRoute
  '/owner': typeof OwnerRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/review': typeof ReviewRoute
  '/instructions/$modeId': typeof InstructionsModeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modes': typeof ModesRoute
  '/owner': typeof OwnerRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/review': typeof ReviewRoute
  '/instructions/$modeId': typeof InstructionsModeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modes': typeof ModesRoute
  '/owner': typeof OwnerRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/review': typeof ReviewRoute
  '/instructions/$modeId': typeof InstructionsModeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modes'
    | '/owner'
    | '/quiz'
    | '/result'
    | '/review'
    | '/instructions/$modeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/modes'
    | '/owner'
    | '/quiz'
    | '/result'
    | '/review'
    | '/instructions/$modeId'
  id:
    | '__root__'
    | '/'
    | '/modes'
    | '/owner'
    | '/quiz'
    | '/result'
    | '/review'
    | '/instructions/$modeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModesRoute: typeof ModesRoute
  OwnerRoute: typeof OwnerRoute
  QuizRoute: typeof QuizRoute
  ResultRoute: typeof ResultRoute
  ReviewRoute: typeof ReviewRoute
  InstructionsModeIdRoute: typeof InstructionsModeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions/$modeId': {
      id: '/instructions/$modeId'
      path: '/instructions/$modeId'
      fullPath: '/instructions/$modeId'
      preLoaderRoute: typeof InstructionsModeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModesRoute: ModesRoute,
  OwnerRoute: OwnerRoute,
  QuizRoute: QuizRoute,
  ResultRoute: ResultRoute,
  ReviewRoute: ReviewRoute,
  InstructionsModeIdRoute: InstructionsModeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
